### ISSUE TITLE
unknown variant `MAXIMUM_CONCURRENT_RUNS_REACHED`

### ISSUE THREAD

**Issue by fedreg-bn** [mach-kernel/databricks-kube-operator#36]
These logs just started popping up in the databricks-kube-operator logs today.

We don't specifically define this field anywhere, only the `max-concurrent-runs` [INT] key

Am able to create new jobs via 2.1 api without sending this field
```
[2023-11-14T19:03:06Z ERROR databricks_kube::traits::remote_api_status] Status sync 
failed for DatabricksJob MY-JOB:
Error calling Databricks API:  Serde(Error("unknown variant `MAXIMUM_CONCURRENT_RUNS_REACHED`, expected one of  `SUCCESS`, `FAILED`, `TIMEDOUT`, `CANCELED`", line: 1, column: 4473)) 
```

**Comment by mach-kernel** [comment]
It looks like we need to update the status enum. I'm on it this morning.
